### PR TITLE
Update for Swift 2.0

### PR DESCRIPTION
**Pull request by a2**

### CODE REVIEW

**Comment by felixvisee** [comment]
:+1:

**Comment by robb** [comment]
Looks sharp, I've made y'all collaborators – would you mind pushing this to a `swift-2.0` branch on this repo that we can use until matters settle? 🙇

**Comment by a2** [comment]
Can do! :)

**Comment by a2** [comment]
Created a [swift-2.0 branch](https://github.com/robb/Monocle/tree/swift-2.0).

**Pull request closed without merging**
